force-app/main/default/objects/CSheet__c/CSheet__c.object-meta.xml
<CustomObject>
    <label>CSheet</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSheet__c/fields/Dexterity__c.field-meta.xml
<CustomField>
    <fullName>Dexterity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dexterity</label>
    <referenceTo>Dexterity__c</referenceTo>
    <relationshipLabel>CSheets</relationshipLabel>
    <relationshipName>CSheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSheet__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Dexterity__c/Dexterity__c.object-meta.xml
<CustomObject>
    <label>Dexterity</label>
    <nameField>
        <label>Dexterity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decterity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Damage__c.field-meta.xml
<CustomField>
    <fullName>Damage__c</fullName>
    <label>Damage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/getMyID.cls
public without sharing class getMyID {

    @AuraEnabled
    public static List<String> getMyId() {
        list<String> myIds = new List<String>();
        
        myIds.add([SELECT id FROM Dexterity__c LIMIT 1].id);
        myIds.add([SELECT id FROM Equipment__c LIMIT 1].id);
        myIds.add([SELECT id FROM CSheet__c LIMIT 1].id);
        
        return myIds;
    }
    
    @AuraEnabled
    public static List<Equipment__c> getEquipment() {
        list<Equipment__c> newList = [SELECT id, Name, Damage__c, Defense__c, Weight__c FROM Equipment__c];        
        return newList;
    }
}