force-app/main/default/objects/Attack__c/Attack__c.object-meta.xml
<CustomObject>
    <label>Attack</label>
    <nameField>
        <label>Attack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attack__c/fields/Damage__c.field-meta.xml
<CustomField>
    <fullName>Damage__c</fullName>
    <label>Damage</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attack__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <label>Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Strength__c/Strength__c.object-meta.xml
<CustomObject>
    <label>Strength</label>
    <nameField>
        <label>Attribute</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strength</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StrengthController.cls
public without sharing class StrengthController {

    @AuraEnabled
    public static List<String> getStrength() {
        List<String> newList = new List<String>();
        
        newList.add([SELECT id FROM Strength__c Limit 1].id);
        newList.add([SELECT id FROM Attack__c Limit 1].id);
        
        return newList;
    }
    
    @AuraEnabled
    public static List<Attack__c> getAttacks() {
        List<Attack__c> attackList = [Select id, Name, Type__c, Range__c, Damage__c FROM Attack__c];
        
        return attackList;
    }
}